# Generated by Django 3.0.5 on 2021-04-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookSession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='isCompleted',
        ),
        migrations.RemoveField(
            model_name='session',
            name='isConfirmed',
        ),
        migrations.RemoveField(
            model_name='session',
            name='isRejected',
        ),
    ]
