# Generated by Django 3.0.5 on 2021-04-06 08:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookSession', '0002_auto_20210403_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slot',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='bookSession.timeSlots'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=2400)),
        ),
    ]
