# Generated by Django 3.0.5 on 2021-04-03 20:04

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210403_2034'),
        ('child', '0003_auto_20210403_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='childdata',
            name='Courses',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='teacher.CourseData'),
        ),
        migrations.AlterField(
            model_name='childdata',
            name='guardian_first_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
