# Generated by Django 3.0.5 on 2021-04-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_auto_20210403_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childdata',
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='childdata',
            name='subjects',
        ),
    ]
