# Generated by Django 3.0.5 on 2021-04-06 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210406_0943'),
        ('child', '0007_auto_20210406_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdata',
            name='Courses',
            field=djongo.models.fields.ArrayReferenceField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='teacher.CourseData'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childdata',
            name='subjects',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
