# Generated by Django 3.0.5 on 2021-04-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0008_auto_20210406_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childdata',
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='childdata',
            name='subjects',
        ),
    ]
